name: hatarakujikan_tablet
description: A new Flutter project.

publish_to: 'none'

version: 2.1.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  css_colors: ^1.1.1

  cupertino_icons: ^1.0.4
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.1
  cloud_firestore: ^4.0.4
  modal_bottom_sheet: ^2.0.1
  provider: ^6.0.2
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.13
  qr_flutter: ^4.0.0
  flutter_launcher_icons: ^0.9.2
  url_launcher: ^6.0.20
  firebase_remote_config: ^3.0.4
  package_info: ^2.0.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"