name: hatarakujikan_tablet
description: A new Flutter project.

publish_to: 'none'

version: 2.2.3+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  css_colors: ^1.1.1

  cupertino_icons: ^1.0.8
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  modal_bottom_sheet: ^3.0.0
  provider: ^6.1.2
  flutter_spinkit: ^5.2.1
  shared_preferences: ^2.2.3
  qr_flutter: ^4.1.0
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"